Repository advaithsrao/Fraud-Detector, pull requests merged in 2023-10, with the labels that each got.

#10 Added utils for preprocessing and data loading
  config.ini
  notebooks/data_explorer.ipynb
  utils/__init__,py
  utils/cleanup.py
  utils/data_fetch.py
Labels: FRAUD MODELING

#11 Added basic test for utils and updated preprocessor
  .github/workflows/pipeline.yml
  tests/__init__.py
  tests/__pycache__/__init__.cpython-310.pyc
  tests/__pycache__/test_utils.cpython-310-pytest-6.2.5.pyc
  tests/test_utils.py
  utils/cleanup.py
  utils/data_fetch.py
Labels: MAINTAINANCE

#12 Added labeler.py for enron labeling pipeline
  detector/labeler.py
  notebooks/data_explorer.ipynb
  resources/enron/sample/user 1/calendar/1.
  resources/enron/sample/user 1/calendar/10.
  resources/enron/sample/user 1/calendar/11.
  resources/enron/sample/user 1/calendar/12.
  resources/enron/sample/user 1/calendar/2.
  resources/enron/sample/user 1/calendar/3.
  resources/enron/sample/user 1/calendar/4.
  resources/enron/sample/user 1/calendar/5.
  resources/enron/sample/user 1/calendar/6.
  resources/enron/sample/user 1/calendar/7.
  resources/enron/sample/user 1/calendar/8.
  resources/enron/sample/user 1/calendar/9.
  resources/enron/sample/user 2/lt_contracts/1.
  resources/enron/sample/user 2/lt_contracts/10.
  resources/enron/sample/user 2/lt_contracts/11.
  resources/enron/sample/user 2/lt_contracts/12.
  resources/enron/sample/user 2/lt_contracts/13.
  resources/enron/sample/user 2/lt_contracts/14.
  resources/enron/sample/user 2/lt_contracts/15.
  resources/enron/sample/user 2/lt_contracts/16.
  resources/enron/sample/user 2/lt_contracts/17.
  resources/enron/sample/user 2/lt_contracts/18.
  resources/enron/sample/user 2/lt_contracts/19.
  resources/enron/sample/user 2/lt_contracts/2.
  resources/enron/sample/user 2/lt_contracts/20.
  resources/enron/sample/user 2/lt_contracts/21.
  resources/enron/sample/user 2/lt_contracts/22.
  resources/enron/sample/user 2/lt_contracts/23.
  resources/enron/sample/user 2/lt_contracts/24.
  resources/enron/sample/user 2/lt_contracts/25.
  resources/enron/sample/user 2/lt_contracts/26.
  resources/enron/sample/user 2/lt_contracts/27.
  resources/enron/sample/user 2/lt_contracts/28.
  resources/enron/sample/user 2/lt_contracts/29.
  resources/enron/sample/user 2/lt_contracts/3.
  resources/enron/sample/user 2/lt_contracts/30.
  resources/enron/sample/user 2/lt_contracts/31.
  resources/enron/sample/user 2/lt_contracts/4.
  resources/enron/sample/user 2/lt_contracts/5.
  resources/enron/sample/user 2/lt_contracts/6.
  resources/enron/sample/user 2/lt_contracts/7.
  resources/enron/sample/user 2/lt_contracts/8.
  resources/enron/sample/user 2/lt_contracts/9.
  resources/extenal_senders.json
  resources/internal_senders.json
  resources/unique_mails_from_sender.json
  tests/test_labeler.py
  tests/test_utils.py
  utils/cleanup.py
  utils/data_fetch.py
Labels: FRAUD MODELING

#13 Updated preprocessing: Added cleanup code for removing html, unicode, links and updated tests
  detector/labeler.py
  poetry.lock
  pyproject.toml
  tests/test_utils.py
  utils/cleanup.py
  utils/data_fetch.py
Labels: FRAUD MODELING

#15 remove signatures and links and added url_count, contains_replies_forwards
  .github/workflows/pipeline.yml
  README.md
  detector/__pycache__/__init__.cpython-310.pyc
  detector/__pycache__/labeler.cpython-310.pyc
  detector/labeler.py
  poetry.lock
  pyproject.toml
  tests/test_labeler.py
  tests/test_utils.py
  utils/cleanup.py
Labels: MAINTAINANCE

#17 Commented out spacy + nltk based signature detection
  poetry.lock
  pyproject.toml
  utils/cleanup.py
Labels: MAINTAINANCE

#18 Defined Initial version of labeled data for fraud detector
  .github/workflows/pipeline.yml
  README.md
  config.ini
  detector/labeler.py
  notebooks/data_explorer.ipynb
  poetry.lock
  pyproject.toml
  tests/test_labeler.py
  tests/test_utils.py
  utils/cleanup.py
  utils/data_fetch.py
Labels: FRAUD MODELING

#24 Fixed issues with large data and model files and restructured repo
  config.ini
  detector/data_loader.py
  detector/labeler.py
  detector/preprocessor.py
  notebooks/data_explorer.ipynb
  notebooks/lda_analysis.ipynb
  resources/sample_phishing_emails.csv
  resources/sample_social_engineering_emails.csv
  tests/test_data_loader.py
  tests/test_labeler.py
  tests/test_preprocessor.py
  utils/util_data_loader.py
  utils/util_preprocessor.py
Labels: FRAUD MODELING, MAINTAINANCE
